version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=hts
      - POSTGRES_USER=hu-tao-mains
      - POSTGRES_PASSWORD=hu-tao-mains
  hts-svc-facility:
    image: ghcr.io/hu-tao-supremacy/facility-dev:0dd89b7
    ports:
      - 50055:50055
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=hu-tao-mains
      - POSTGRES_PASSWORD=hu-tao-mains
      - POSTGRES_DB=hts
      - POSTGRES_PORT=5432
      - GRPC_HOST=localhost
      - GRPC_PORT=50055
